// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddServer(arg1:string):Promise<void>;

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetState():Promise<app.StateDTO>;

export function HideToTray():Promise<void>;

export function Logs():Promise<Array<string>>;

export function QuitApp():Promise<void>;

export function RelaunchElevated():Promise<void>;

export function RemoveServer(arg1:number):Promise<void>;

export function SetActiveServer(arg1:number):Promise<void>;

export function UpdateProfile(arg1:app.ProfileDTO):Promise<void>;

export function UpdateSettings(arg1:app.SettingsDTO):Promise<void>;
